version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: motobyo
      POSTGRES_PASSWORD: motobyo
      POSTGRES_DB: motobyo